@host = http://localhost:8082

### логін
POST {{host}}/api/login
Content-Type: application/json

{
"login": "super_admin",
"password": "super_admin"
}

### логін refresh
POST {{host}}/api/login/refresh
Content-Type: application/json

{
"refreshToken": "c4b45610-d8e2-475c-a213-333a22d125dd"
}

### Створення видів послуги
POST {{host}}/api/service-type/add
Content-Type: application/json

      {
        "serviceType": "logo",
        "displayName": "logo"
        }

### Створення нової організації з налаштуваннями
POST {{host}}/api/organizations/crud/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic2NvcGUiOiJTVVBFUl9BRE1JTiIsInN1YiI6IjEiLCJpYXQiOjE3Njk5NDQ3NTgsImV4cCI6MTc3MDAzMTE1OH0.hJEBvCd0w0Cyn5Nlul_xUYnksRSzGUpJE5Nxb-szcuM
Content-Type: application/json

        {
            "organizationName": "Організація24",
            "organizationCity": "Київ",
            "settingLessonsTimesList": [
            {
            "lessonType": "INDIVIDUAL",
            "firstHourOfWork": "09:00",
            "lastHourOfWork": "18:00",
            "lessonDurationMinutes": 45,
            "breakDurationMinutes": 15
            },
            {
            "lessonType": "GROUP",
            "firstHourOfWork": "10:00",
            "lastHourOfWork": "19:00",
            "lessonDurationMinutes": 50,
            "breakDurationMinutes": 10
            }
            ],
            "priceList": [
            {
            "serviceType":  { "id": 2 },
            "valueOnePay": 350
            }
            ]
        }



### Створення персоналу
POST {{host}}/api/employee/add
Content-Type: application/json

  {
      "login": "employee",
      "password": "employee",
      "name": "emp",
      "lastName": "emp;",
      "phone": "Phone"
        }


### Створення контракту
POST {{host}}/api/employee/contracts/add
Content-Type: application/json

{
"employee": {"id": 2},
"organization": {"id": 7},
"masterEmployee": null,
"salary": [
        {
            "serviceType": {"id": 2},
            "value": 170,
            "premiumValue": null,
            "lessonType" : "INDIVIDUAL"
        },
        {
            "serviceType": {"id": 2},
            "value": 100,
            "premiumValue": null,
            "lessonType" : "GROUP"
        }
        ],
"role": "admin"
        }

### Створення клієнта
POST {{host}}/api/clients/add
Content-Type: application/json

{
"login": "login24",
"password": "pass",
"phone": "095111111",
"name": "Dima",
    "organization": {"id":  2},
    "photoPermission": true,
    "sourceClient": "OLX",
    "children": [
    {
    "name": "Mira",
    "lastName":"Dmytrovna",
    "secondName": "Sydorenko",
    "birthdayDate":"2021-08-11",
    "interests": "molot huiny",
    "requestForLessons":"RRRRR",
    "diagnosis": null
    }
    ]

}

### Вимкнути клієнта
POST {{host}}/api/clients/disable
Content-Type: application/json

{
"id": 4
}

### Створити динину клієнтом
POST {{host}}/api/child/add/client
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6IkNMSUVOVCIsImlkIjozLCJzdWIiOiIzIiwiaWF0IjoxNzY5NDYwNzM5LCJleHAiOjE3Njk1NDcxMzl9.5zXYNzEZ7WrcnX3hXOa6X-q9zPRilj-bhSXKS0F7w2o
Content-Type: application/json

{
    "name":  "child2",
    "lastName": "sgddgh",
    "secondName":  "sdfgh",
    "birthdayDate": "1884-11-11",
    "interests":  "sgdfh",
    "requestForLessons": null,
    "diagnosis": ""
}

### Створити динину Адміном
POST {{host}}/api/child/add/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6IlNVUEVSX0FETUlOIiwiaWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3Njk0NjIyMDcsImV4cCI6MTc2OTU0ODYwN30.ZgDOpfl65skH5tecFRnKzUzNWe6uu4P-exMp_0l4oUs
Content-Type: application/json

{
    "client": {"id": 3},
    "name": "child2333",
    "lastName": "sgddgh",
    "secondName": "sdfgh",
    "birthdayDate": "1884-11-11",
    "interests": "sgdfh",
    "requestForLessons": null,
    "diagnosis": ""
}

### Створити заняття
POST {{host}}/api/lesson/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic2NvcGUiOiJTVVBFUl9BRE1JTiIsInN1YiI6IjEiLCJpYXQiOjE3Njk5NDQ3NTgsImV4cCI6MTc3MDAzMTE1OH0.hJEBvCd0w0Cyn5Nlul_xUYnksRSzGUpJE5Nxb-szcuM
Content-Type: application/json

{
    "lessonStatus" : "WAIT",
    "child" : null,
    "serviceType" : {"id": 2},
    "lessonType" : "GROUP",
    "lessonDateTime" : "2026-02-02T11:00",
    "lessonEndTime" : "2026-02-02T12:57",
    "organization" : {"id" :  7},
    "employee" : {"id" : 2},
    "comments" : "test"
}
