@host = http://localhost:8082
@token = eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6IlNVUEVSX0FETUlOIEFETUlOIiwiaWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NzEzNTg1MzIsImV4cCI6MTc3MTQ0NDkzMn0.14pI1hVnaR7ZrGJpAbhsBuW923Px7eQntvLUq3lwM1s

### логін
POST {{host}}/api/login
Content-Type: application/json

{
"login": "super_admin",
"password": "super_admin"
}

### логін refresh
POST {{host}}/api/login/refresh
Content-Type: application/json

{
"refreshToken": "c4b45610-d8e2-475c-a213-333a22d125dd"
}

### Створення видів послуги
POST {{host}}/api/service-type/add
Authorization: Bearer {{token}}
Content-Type: application/json

      {
        "serviceType": "logo",
        "displayName": "logo"
        }

### Створення нової організації з налаштуваннями
POST {{host}}/api/organizations/crud/add
Authorization: Bearer {{token}}
Content-Type: application/json

        {
            "organizationName": "Організація24",
            "organizationCity": "Київ",
            "settingLessonsTimesList": [
            {
            "lessonType": "INDIVIDUAL",
            "firstHourOfWork": "09:00",
            "lastHourOfWork": "18:00",
            "lessonDurationMinutes": 45,
            "breakDurationMinutes": 15
            },
            {
            "lessonType": "GROUP",
            "firstHourOfWork": "10:00",
            "lastHourOfWork": "19:00",
            "lessonDurationMinutes": 50,
            "breakDurationMinutes": 10
            }
            ],
            "priceList": [
            {
            "serviceTypeId": 2,
            "valueOnePay": 350
            }
            ]
        }



### Створення персоналу
POST {{host}}/api/employee/add
Authorization: Bearer {{token}}
Content-Type: application/json

  {
      "login": "employee6",
      "password": "employee",
      "name": "employee3",
      "lastName": "employee",
      "phone": "Phone"
        }


### Створення контракту
POST {{host}}/api/employee/contracts/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
"employeeId": 7,
"organizationId": 2,
"masterEmployeeId": null,
"salary": [
        {
            "serviceTypeId": 2,
            "value": 170,
            "premiumValue": null,
            "lessonType" : "INDIVIDUAL"
        },
        {
            "serviceTypeId": 2,
            "value": 100,
            "premiumValue": null,
            "lessonType" : "GROUP"
        }
        ],
"role": "employee"
        }

### Створення клієнта
POST {{host}}/api/clients/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
"login": "login25",
"password": "pass",
"phone": "095111111",
"name": "Dima",
    "organizationId": 2,
    "photoPermission": true,
    "sourceClient": "OLX",
    "children": [
    {
    "name": "Mira",
    "lastName":"Sydorenko",
    "secondName": "Dmytrovna",
    "birthdayDate":"2021-08-11",
    "interests": "molot huiny",
    "requestForLessons":"RRRRR",
    "diagnosis": null
    }
    ]

}

### Додати Організацію Клієнту
POST {{host}}/api/clients/add_organization
Authorization: Bearer {{token}}
Content-Type: application/json

{
"clientId": 2,
"organizationId": 1
}

### Вимкнути ентіті
POST {{host}}/api/child/enable
Authorization: Bearer {{token}}
Content-Type: application/json

{
"id": 1
}

### Створити динину клієнтом
POST {{host}}/api/child/add/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":  "child2",
    "lastName": "sgddgh",
    "secondName":  "sdfgh",
    "birthdayDate": "1884-11-11",
    "interests":  "sgdfh",
    "requestForLessons": null,
    "diagnosis": ""
}

### Створити динину Адміном
POST {{host}}/api/child/add/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "clientId": 2,
    "name": "child2333",
    "lastName": "sgddgh",
    "secondName": "sdfgh",
    "birthdayDate": "1884-11-11",
    "interests": "sgdfh",
    "requestForLessons": null,
    "diagnosis": ""
}

### Створити заняття
POST {{host}}/api/lesson/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "lessonStatus" : null,
    "childId" : 1,
    "serviceTypeId" : 2,
    "lessonType" : "GROUP",
    "lessonDateTime" : "2026-02-12T15:00",
    "lessonEndTime" : "2026-02-12T15:45",
    "organizationId" : 2,
    "employeeId" : 2,
    "comments" : "test"
}

### Отримати графік на період
POST {{host}}/api/schedule/period
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "startDate": "2026-02-02",
    "endDate": "2026-02-16",
    "organizationId": 2
}

### Отримати cписок дітей на організацію
POST {{host}}/api/schedule/childNames
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "organizationId": 2
}